// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAL6MtoCV6s5RAD6cOAr4QO4bVEZd7OnQ',
    appId: '1:779304236953:web:28b02acb452a4cc4404508',
    messagingSenderId: '779304236953',
    projectId: 'kendo-os',
    authDomain: 'kendo-os.firebaseapp.com',
    storageBucket: 'kendo-os.firebasestorage.app',
    measurementId: 'G-V0EJ5687SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw_EqGL7LebEhwcQ0YvFNEXdpJby0uenA',
    appId: '1:779304236953:android:58bbd2ed68a2045c404508',
    messagingSenderId: '779304236953',
    projectId: 'kendo-os',
    storageBucket: 'kendo-os.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb716n_0IomzzeCnsQSjMB31AdXyOzNO4',
    appId: '1:779304236953:ios:ff3ce534b071263d404508',
    messagingSenderId: '779304236953',
    projectId: 'kendo-os',
    storageBucket: 'kendo-os.firebasestorage.app',
    iosBundleId: 'com.example.kendoOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb716n_0IomzzeCnsQSjMB31AdXyOzNO4',
    appId: '1:779304236953:ios:ff3ce534b071263d404508',
    messagingSenderId: '779304236953',
    projectId: 'kendo-os',
    storageBucket: 'kendo-os.firebasestorage.app',
    iosBundleId: 'com.example.kendoOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAL6MtoCV6s5RAD6cOAr4QO4bVEZd7OnQ',
    appId: '1:779304236953:web:a46a5e18d8a2913f404508',
    messagingSenderId: '779304236953',
    projectId: 'kendo-os',
    authDomain: 'kendo-os.firebaseapp.com',
    storageBucket: 'kendo-os.firebasestorage.app',
    measurementId: 'G-3VXZB62KG0',
  );
}
